# Generated by Django 4.2 on 2025-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('new', 'Принята'), ('in_progress', 'В работе'), ('ready', 'Готов к выдаче'), ('successful', 'Успешная'), ('closed', 'Закрытая')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
